version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  pgadmin4:
    image: elestio/pgadmin
    restart: always
    environment:
      PGADMIN_LISTEN_PORT: 8080
      PGADMIN_DEFAULT_EMAIL: test@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "127.0.0.1:8080:8080"
